POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   "title": "100 likes",
   "author": "khalil",
   "url": "http://example.com/100",
   "likes": 100,
   "userId": "69f35f0633f406e7cc811d71"
}
